import { ConvexError } from "convex/values";

export const NEXUS_ERROR_CODES = {
  UNAUTHENTICATED: "unauthenticated",
  APPROVAL_REQUIRED: "approval_required",
  USER_SUSPENDED: "user_suspended",
  FORBIDDEN: "forbidden",
  ROLE_REQUIRED: "role_required",
  USER_NOT_FOUND: "user_not_found",
  ROLE_ALREADY_GRANTED: "role_already_granted",
  ROLE_NOT_ACTIVE: "role_not_active",
  LAST_ADMIN: "last_admin",
  INVALID_INPUT: "invalid_input",
  // P5 — private conversations, tasks, and shared queue.
  CONVERSATION_NOT_FOUND: "conversation_not_found",
  MESSAGE_NOT_FOUND: "message_not_found",
  TASK_NOT_FOUND: "task_not_found",
  INVALID_TASK_STATE: "invalid_task_state",
  INVALID_TOOL: "invalid_tool",
  REQUEST_TOO_LARGE: "request_too_large",
  IDEMPOTENCY_CONFLICT: "idempotency_conflict",
  RETRY_NOT_ALLOWED: "retry_not_allowed",
  CANCELLATION_NOT_ALLOWED: "cancellation_not_allowed",
  QUEUE_UNAVAILABLE: "queue_unavailable",
  RESULT_NOT_AVAILABLE: "result_not_available",
  // P6 — trusted Connector queue protocol.
  CONNECTOR_UNAUTHORIZED: "connector_unauthorized",
  CONNECTOR_DISABLED: "connector_disabled",
  CONNECTOR_REVOKED: "connector_revoked",
  INVALID_SIGNATURE: "invalid_signature",
  STALE_TIMESTAMP: "stale_timestamp",
  REPLAY_DETECTED: "replay_detected",
  INVALID_REQUEST: "invalid_request",
  BODY_TOO_LARGE: "body_too_large",
  NO_TASK_AVAILABLE: "no_task_available",
  CONNECTOR_BUSY: "connector_busy",
  TASK_NOT_CLAIMED: "task_not_claimed",
  WRONG_CONNECTOR: "wrong_connector",
  WRONG_LEASE: "wrong_lease",
  LEASE_EXPIRED: "lease_expired",
  CANCELLATION_REQUESTED: "cancellation_requested",
  COMPLETION_CONFLICT: "completion_conflict",
  RESULT_TOO_LARGE: "result_too_large",
  TOO_MANY_SOURCES: "too_many_sources",
  PROGRESS_TOO_LARGE: "progress_too_large",
  PROTOCOL_VERSION_UNSUPPORTED: "protocol_version_unsupported",
  INTERNAL_ERROR: "internal_error",
  // P6/P7 — task-bound attachment download.
  ATTACHMENT_NOT_FOUND: "attachment_not_found",
  ATTACHMENT_NOT_BOUND: "attachment_not_bound",
  ATTACHMENT_VERSION_MISMATCH: "attachment_version_mismatch",
  ATTACHMENT_UNAVAILABLE: "attachment_unavailable",
  ATTACHMENT_STORAGE_UNAVAILABLE: "attachment_storage_unavailable",
  ATTACHMENT_METADATA_MISMATCH: "attachment_metadata_mismatch",
  ATTACHMENT_TOO_LARGE: "attachment_too_large",
  UNSUPPORTED_ATTACHMENT_ACTION: "unsupported_attachment_action",
  ATTACHMENT_READ_FAILED: "attachment_read_failed",
  LIBRARY_VERSION_NOT_FOUND: "library_version_not_found",
  LIBRARY_DOCUMENT_NOT_FOUND: "library_document_not_found",
  LIBRARY_PROCESS_NOT_ALLOWED: "library_process_not_allowed",
  LIBRARY_ACTIVE_TASK_EXISTS: "library_active_task_exists",
  LIBRARY_UNSUPPORTED_FORMAT: "library_unsupported_format",
  LIBRARY_UPLOAD_TOO_LARGE: "library_upload_too_large",
  LIBRARY_UPLOAD_INVALID: "library_upload_invalid",
  // Nexus Calendar — scheduled task dispatch.
  SCHEDULED_EVENT_NOT_FOUND: "scheduled_event_not_found",
  SCHEDULED_EVENT_NOT_EDITABLE: "scheduled_event_not_editable",
  SCHEDULED_EVENT_NOT_DELETABLE: "scheduled_event_not_deletable",
  SCHEDULED_EVENT_INVALID_TIME: "scheduled_event_invalid_time",
  SCHEDULED_TOOL_UNAVAILABLE: "scheduled_tool_unavailable",
  NOTE_NOT_FOUND: "note_not_found",
  NOTE_INVALID: "note_invalid",
} as const;

export type NexusErrorCode =
  (typeof NEXUS_ERROR_CODES)[keyof typeof NEXUS_ERROR_CODES];

export function nexusError(code: NexusErrorCode, message: string): never {
  throw new ConvexError({ code, message });
}
